export const AUTH_ERRORS = {
  MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
  INVALID_EMAIL: "INVALID_EMAIL",
  NO_PASSWORD_ACCOUNT: "NO_PASSWORD_ACCOUNT",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
} as const;

export type AuthErrorCode =
  typeof AUTH_ERRORS[keyof typeof AUTH_ERRORS];